### ISSUE TITLE
how to get all of the selected sites by different selective methods

### ISSUE THREAD

**Issue by ZhangMin-123** [claununez/biosurvey#28]
thanks for your wonderful work on the package "biosurvey", I am learning it and try to use it in our work involving in biodiversity survey in river. But i find that these file-"EG_sel，EG_r_G_E-selection" didn't show the longitudes and latitudes of all of the selected sites. SO I can not use it to locate the site information.
![1652427806(1)](https://user-images.githubusercontent.com/87161185/168235776-a25bcdb7-634f-457a-b356-09d2188209e0.jpg)
![1652427903(1)](https://user-images.githubusercontent.com/87161185/168236020-7c39f268-31e6-42c7-aa31-ec1340068d51.jpg)

**Comment by marlonecobos** [comment]
Hi @ZhangMin-123, thanks for using the package. The object that contains the result from site selection functions is a list. As such, you can select specific parts of this list to be seen or saved the way you need. For instance, if the object resulting from `EG_selection` is called `eg_sel`, you can do `eg_sel$selected_sites_EG` and obtain the list of `data.frames` with results. Each of those `data.frames` (it can also be just one) is a result of the selection. You can pick one of those  `data.frames`, store it in another object, and do other stuff with it. For instance, save it as a CSV file.
