### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [claununez/biosurvey#29]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

`biosurvey` uses `rgdal::readOGR`,  `rgeos::gBuffer`,  `rgeos::gCentroid` in code, and may use retiring packages elsewhere. Note that `sp::over` may also stop working when `rgeos` retires. Action is required urgently to pass CMD check in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path.

**Comment by rsbivand** [comment]
Expect package to fail CRAN CMD check with `_R_CHECK_SUGGESTS_ONLY_=true` when `sp` 2.0-0 is published very soon, if `sf` is not added to Suggests:

**Comment by rsbivand** [comment]
The CRAN check errors are piling up: https://cran.r-project.org/web/checks/check_results_biosurvey.html. Please take action as indicated.

**Comment by marlonecobos** [comment]
Thanks, we have finished with the changes to prevent similar errors. Will be submitting to CRAN soon.
